travis:
  secure:
    BINSTAR_TOKEN: uvfRyTSdZ6F4XjtDZmTbJSQZQ8ERT7b3Sit+ylcbBCHcS9GiRy0egRbKBn05aP6pTpi3l8W/AkexgeD3aKlps+SgORYKfbx7HtOD3uR8TZFay/LX9z4yNZoDGZOO2U2IB1oImAwTvY3NHg4BCM7K8CwGNe+/s9kr15tvDqM2nM8WrQhZLO3ZuPa/eFwvXBfBeQP5S6TAZGDdNuua78Hzwy5Zy/noFYU5MHsCZtiR8rpM79iMK9AjoXz4x1hQsIwqk12cYe4zLg1lJE+hi+oT9mZC8KWFkytiwUHaxtmZoP5BntqtuMG1ZE6p39sb6I7nlTC1omKFeStr1rF3eb93zDdwy3TF4FRS8kpJuRIZ6ndrUm0khELKo921u0YC53uQVNOwZS+nAxsMt4FwcafIDEtnP7q/scI6w79S9R4L8dFi90LSlSGtzl8qsr9PND4d3swchQOrHk64nfijt997um6x16vxnRMP+jBDj5pFaQRduDMnFJkLBc4Pp/3V3q55lnPdRfwwCTQGW9BJvkqrS9VIkmzBHcPRdT0MRF9nIDatc2Kval4UX2dfd+GeUQxiO/kANH0SuY9If7DWuD4hlw/SSMm3QOzfPzFxh3pCRccq2WCF1KyrgNRo6zAOZ3rYg2EN0eshaI1flUHBeOnmTgp4raEp9s18nLmUu6MN0Is=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
